---
# tasks file for ufw

- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install ufw
  package:
    name: "{{ ufw_package_names }}"

- name: Configure UFW logging and state
  ufw:
    logging: "{{ logging }}"
    state: "{{ state }}"

# Unless you do this, systemd can sometimes get confused when you try
# to enable a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable the UFW service
  service:
    name: ufw
    enabled: yes
