---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install UFW
  ansible.builtin.package:
    name: "{{ ufw_package_names }}"

- name: Reload the SystemD daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Configure UFW logging and state
  community.general.ufw:
    logging: "{{ ufw_logging }}"
    state: "{{ ufw_state }}"

# The following updates to /etc/ufw/sysctl.conf are done to harden
# the operating system and are good general security practices.
#
# Note that /etc/ufw/sysctl.conf values overwrite those in /etc/sysctl.conf
# which is why these changes are made here, rather than in
# https://github.com/cisagov/ansible-role-hardening
- name: Log martian (impossible address) packets
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: "(?i)[^\\s #]*{{ item.name }}"
    line: "{{ item.name }}={{ item.value }}"
    state: present
  loop:
    - { name: "net/ipv4/conf/all/log_martians", value: "1"}
    - { name: "net/ipv4/conf/default/log_martians", value: "1"}

- name: Enable TCP SYN cookies
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: "(?i)[^\\s #]*net/ipv4/tcp_syncookies"
    line: "net/ipv4/tcp_syncookies=1"
    state: present

# The ufw systemd unit file in Kali Linux currently introduces a
# dependency cycle that causes the cloud-init service not to run at
# boot even if enabled.  (systemd refuses to run cloud-init.service in
# order to break the cycle.)  Therefore we have to make a few fixes
# here.
- name: Fix buggy lines in Kali ufw.service unit file
  when: ansible_distribution == "Kali"
  block:
    - name: Remove buggy Wants line in Kali ufw.service unit file
      ansible.builtin.lineinfile:
        line: Wants=network-pre.target
        path: /usr/lib/systemd/system/ufw.service
        state: absent
    - name: Add DefaultDependencies line in Kali ufw.service unit file
      ansible.builtin.lineinfile:
        insertbefore: ^Before=network-pre\.target$
        line: DefaultDependencies=no
        path: /usr/lib/systemd/system/ufw.service


# Unless you do this, systemd can sometimes get confused when you try
# to enable a service you just installed
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable the UFW service
  ansible.builtin.service:
    name: ufw
    enabled: yes
