---
# tasks file for ufw

- name: Install ufw
  package:
    name:
      - ufw

- name: Enable the UFW service
  service:
    name: ufw
    enabled: yes

- name: Configure the UFW service
  ufw:
    logging: "{{ logging }}"
    state: "{{ state }}"
