---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  # Amazon Linux does not appear to offer ufw
  # - name: amazonlinux2_systemd
  #   image: geerlingguy/docker-amazonlinux2-ansible:latest
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /lib/systemd/systemd
  #   pre_build_image: yes
  - name: debian9_systemd
    image: geerlingguy/docker-debian9-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: debian10_systemd
    image: geerlingguy/docker-debian10-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: debian11_systemd
    image: cisagov/docker-debian11-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: kali_systemd
    image: cisagov/docker-kali-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: fedora32_systemd
    image: geerlingguy/docker-fedora32-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: fedora33_systemd
    image: cisagov/docker-fedora33-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  # For reasons I haven't been able to discern, the Ubuntu molecule
  # tests work fine locally but fail in GitHub Actions due to being
  # unable to perform some iptables operations.  I would think this
  # was due to some kernel module not being loaded in the underlying
  # host instance, except that the non-Ubuntu platforms pass just fine
  # in GitHub Actions.
  #
  # I've already spent too much time on this, and we don't require the
  # Ubuntu support right now, so I will make the executive decision to
  # remove Ubuntu support for now.  I created this issue to document
  # the error:
  # https://github.com/cisagov/ansible-role-ufw/issues/3
  # - name: ubuntu_bionic_systemd
  #   image: geerlingguy/docker-ubuntu1604-ansible:latest
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /lib/systemd/systemd
  #   pre_build_image: yes
  # - name: ubuntu_xenial_systemd
  #   image: geerlingguy/docker-ubuntu1804-ansible:latest
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /lib/systemd/systemd
  #   pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      # The OS family and distribution for Kali is "Kali GNU/Linux",
      # which is not an allowable group name in Ansible due to the
      # space and the slash.  This option converts those characters to
      # underscores when creating the group name.
      force_valid_group_names: always
scenario:
  name: default
verifier:
  name: testinfra
